Document: pulseaudio-modules-bt
Title: Debian pulseaudio-modules-bt Manual
Author: <insert document author here>
Abstract: This manual describes what pulseaudio-modules-bt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pulseaudio-modules-bt/pulseaudio-modules-bt.sgml.gz

Format: postscript
Files: /usr/share/doc/pulseaudio-modules-bt/pulseaudio-modules-bt.ps.gz

Format: text
Files: /usr/share/doc/pulseaudio-modules-bt/pulseaudio-modules-bt.text.gz

Format: HTML
Index: /usr/share/doc/pulseaudio-modules-bt/html/index.html
Files: /usr/share/doc/pulseaudio-modules-bt/html/*.html
